services:
  backend:
    build: 
      context: ./backend-nodejs
      dockerfile: Dockerfile
    container_name: polkadot-nft-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://attendance_nft_db_user:jakMxfqctlrET5cnO0wxLroHdmM57yx8@dpg-d0lq7u8dl3ps73bn64ng-a.frankfurt-postgres.render.com/attendance_nft_db
      JWT_SECRET: dev-jwt-secret-key-very-long-and-secure
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: http://localhost:3000,http://frontend:3000
      POLKADOT_RPC_URL: wss://ws.test.azero.dev
      CONTRACT_ADDRESS: 5GvobTJcPvkYq8yYK66eitzt4AeLMuB85sYq8YMTwsq8KanA
      SIGNER_MNEMONIC: "denial clip diesel pool peasant garment price sick person cabin fabric million"
      RATE_LIMIT_ENABLED: false
      RATE_LIMIT_REQUESTS_PER_MINUTE: 100
      EVENT_POLL_INTERVAL: 10000
      CHECKIN_POLL_INTERVAL: 5000
      # Email service configuration
      EMAIL_ENABLED: true
      EMAIL_SERVICE: gmail
      EMAIL_USER: samwriting45@gmail.com
      EMAIL_APP_PASSWORD: iroz sdci jciq cmew
      EMAIL_FROM: samwriting45@gmail.com
    depends_on: []
    volumes:
      - ./backend-nodejs/src:/app/src
      - ./backend-nodejs/prisma:/app/prisma
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: polkadot-nft-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_WS_URL: ws://localhost:3001
      NODE_OPTIONS: "--max-old-space-size=4096"
      GENERATE_SOURCEMAP: "false"
      FAST_REFRESH: "true"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped