version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: polkadot-nft-db
    environment:
      POSTGRES_DB: polkadot_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend-nodejs
    container_name: polkadot-nft-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/polkadot_attendance
      JWT_SECRET: dev-jwt-secret-key
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      POLKADOT_RPC_URL: wss://ws.test.azero.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend-nodejs/src:/app/src
      - ./backend-nodejs/prisma:/app/prisma
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: polkadot-nft-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_WS_URL: ws://localhost:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm start
    depends_on:
      - backend

volumes:
  postgres_data: