services:
  - type: web
    name: polkadot-attendance-nft-api
    env: go
    buildCommand: cd cmd/server && go build -o main .
    startCommand: cd cmd/server && ./main
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: GO_ENV
        value: production
      - key: CONTRACT_ADDRESS
        value: 5HAQRFusUjYdNLchvrWe632orYgr615g2ePGj7DkShX3go1j
      - key: API_KEY
        generateValue: true  # Generate a random value on first deploy
      - key: CORS_ORIGIN
        value: https://polkadot-attendance-nft.netlify.app 